import { createSelectSchema } from "drizzle-zod";
import { usersTable } from "./schema/users";
import { sessionsTable } from "./schema/users";
import { accountsTable } from "./schema/accounts";
import { categoriesTable } from "./schema/categories";
import { contactsTable } from "./schema/contacts";
import { locationsTable } from "./schema/locations";
import { transactionsTable, transactionContactsTable } from "./schema/transactions";
import { recurringRulesTable } from "./schema/recurring-rules";
import { settingsTable } from "./schema/settings";
import { syncLogTable } from "./schema/sync-log";

export const userSelectSchema = createSelectSchema(usersTable);
export const sessionSelectSchema = createSelectSchema(sessionsTable);
export const accountSelectSchema = createSelectSchema(accountsTable);
export const categorySelectSchema = createSelectSchema(categoriesTable);
export const contactSelectSchema = createSelectSchema(contactsTable);
export const locationSelectSchema = createSelectSchema(locationsTable);
export const transactionSelectSchema = createSelectSchema(transactionsTable);
export const transactionContactSelectSchema = createSelectSchema(transactionContactsTable);
export const recurringRuleSelectSchema = createSelectSchema(recurringRulesTable);
export const settingSelectSchema = createSelectSchema(settingsTable);
export const syncLogSelectSchema = createSelectSchema(syncLogTable);
