/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as DashboardImport } from './routes/_dashboard'

// Create Virtual Routes

const AuthLazyImport = createFileRoute('/auth')()
const IndexLazyImport = createFileRoute('/')()
const DashboardStatsLazyImport = createFileRoute('/_dashboard/stats')()
const DashboardTransactionsIndexLazyImport = createFileRoute(
  '/_dashboard/transactions/',
)()
const DashboardProfileIndexLazyImport = createFileRoute(
  '/_dashboard/profile/',
)()
const DashboardAccountsIndexLazyImport = createFileRoute(
  '/_dashboard/accounts/',
)()

// Create/Update Routes

const AuthLazyRoute = AuthLazyImport.update({
  path: '/auth',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/auth.lazy').then((d) => d.Route))

const DashboardRoute = DashboardImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRoute,
} as any)

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const DashboardStatsLazyRoute = DashboardStatsLazyImport.update({
  path: '/stats',
  getParentRoute: () => DashboardRoute,
} as any).lazy(() =>
  import('./routes/_dashboard/stats.lazy').then((d) => d.Route),
)

const DashboardTransactionsIndexLazyRoute =
  DashboardTransactionsIndexLazyImport.update({
    path: '/transactions/',
    getParentRoute: () => DashboardRoute,
  } as any).lazy(() =>
    import('./routes/_dashboard/transactions/index.lazy').then((d) => d.Route),
  )

const DashboardProfileIndexLazyRoute = DashboardProfileIndexLazyImport.update({
  path: '/profile/',
  getParentRoute: () => DashboardRoute,
} as any).lazy(() =>
  import('./routes/_dashboard/profile/index.lazy').then((d) => d.Route),
)

const DashboardAccountsIndexLazyRoute = DashboardAccountsIndexLazyImport.update(
  {
    path: '/accounts/',
    getParentRoute: () => DashboardRoute,
  } as any,
).lazy(() =>
  import('./routes/_dashboard/accounts/index.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/_dashboard': {
      preLoaderRoute: typeof DashboardImport
      parentRoute: typeof rootRoute
    }
    '/auth': {
      preLoaderRoute: typeof AuthLazyImport
      parentRoute: typeof rootRoute
    }
    '/_dashboard/stats': {
      preLoaderRoute: typeof DashboardStatsLazyImport
      parentRoute: typeof DashboardImport
    }
    '/_dashboard/accounts/': {
      preLoaderRoute: typeof DashboardAccountsIndexLazyImport
      parentRoute: typeof DashboardImport
    }
    '/_dashboard/profile/': {
      preLoaderRoute: typeof DashboardProfileIndexLazyImport
      parentRoute: typeof DashboardImport
    }
    '/_dashboard/transactions/': {
      preLoaderRoute: typeof DashboardTransactionsIndexLazyImport
      parentRoute: typeof DashboardImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexLazyRoute,
  DashboardRoute.addChildren([
    DashboardStatsLazyRoute,
    DashboardAccountsIndexLazyRoute,
    DashboardProfileIndexLazyRoute,
    DashboardTransactionsIndexLazyRoute,
  ]),
  AuthLazyRoute,
])

/* prettier-ignore-end */
